name: Generate ASCII Artwork
on:
    push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt-get install cowsay -y
            - run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
            - run: sleep 30

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10
            - run: grep -i "dragon" dragon.txt

    deploy_job:
        needs: test_job
        runs-on: ubuntu-sleep
        steps:
            - run: cat dragon.txt
            - run: echo deploying...